In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('https://github.com/prasertcbs/basic-dataset/raw/master/study_hours.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   20 non-null     float64
 1   Pass    20 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 448.0 bytes


In [4]:
df.isnull().sum()

Hours    0
Pass     0
dtype: int64

In [5]:
df.describe()

Hours       Pass
count  20.000000  20.000000
mean    2.787500   0.500000
std     1.507165   0.512989
min     0.500000   0.000000
25%     1.687500   0.000000
50%     2.625000   0.500000
75%     4.062500   1.000000
max     5.500000   1.000000

In [7]:
X,y=df[['Hours']],df['Pass']

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn import metrics
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=7)

In [11]:
X_train

Hours
18   5.00
6    1.75
13   3.50
19   5.50
10   2.75
14   4.00
8    2.25
16   4.50
9    2.50
12   3.25
7    2.00
3    1.25
4    1.50
15   4.25

In [12]:
X_test

Hours
1    0.75
17   4.75
2    1.00
5    1.75
11   3.00
0    0.50

In [13]:
model = LogisticRegression()

In [14]:
model.fit(X_train,y_train)

LogisticRegression()

In [16]:
model.coef_

array([[0.92276914]])

In [17]:
pred=model.predict(X_test)
pred

array([0, 1, 0, 0, 1, 0], dtype=int64)

In [19]:
y_test.values

array([0, 1, 0, 0, 0, 0], dtype=int64)