In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
%config InlineBackend.figure_format='retina'

In [22]:
data=pd.read_csv('https://github.com/prasertcbs/basic-dataset/raw/master/iris.csv')
data.sample(10)

sepal_length  sepal_width  petal_length  petal_width     species
91            6.1          3.0           4.6          1.4  versicolor
49            5.0          3.3           1.4          0.2      setosa
46            5.1          3.8           1.6          0.2      setosa
0             5.1          3.5           1.4          0.2      setosa
94            5.6          2.7           4.2          1.3  versicolor
90            5.5          2.6           4.4          1.2  versicolor
59            5.2          2.7           3.9          1.4  versicolor
61            5.9          3.0           4.2          1.5  versicolor
127           6.1          3.0           4.9          1.8   virginica
19            5.1          3.8           1.5          0.3      setosa

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [24]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [25]:
data.species.value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [27]:
X=data[['sepal_length','sepal_width','petal_length','petal_width']]
y=data['species']

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=7)

In [29]:
X_train


sepal_length  sepal_width  petal_length  petal_width
49            5.0          3.3           1.4          0.2
65            6.7          3.1           4.4          1.4
62            6.0          2.2           4.0          1.0
111           6.4          2.7           5.3          1.9
29            4.7          3.2           1.6          0.2
..            ...          ...           ...          ...
142           5.8          2.7           5.1          1.9
92            5.8          2.6           4.0          1.2
103           6.3          2.9           5.6          1.8
67            5.8          2.7           4.1          1.0
25            5.0          3.0           1.6          0.2

[105 rows x 4 columns]

In [30]:
model = KNeighborsClassifier()
model

KNeighborsClassifier()

In [31]:
model.fit(X_train,y_train)

KNeighborsClassifier()

In [41]:
model.score(X_train,y_train)

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9809523809523809

In [43]:
pred=model.predict(X_test)

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [44]:
dataex=pd.DataFrame({'true':y_test,'pred':pred})

In [45]:
dataex

true        pred
149   virginica   virginica
84   versicolor  versicolor
40       setosa      setosa
66   versicolor  versicolor
106   virginica  versicolor
41       setosa      setosa
52   versicolor  versicolor
94   versicolor  versicolor
11       setosa      setosa
51   versicolor  versicolor
77   versicolor   virginica
85   versicolor  versicolor
32       setosa      setosa
109   virginica   virginica
28       setosa      setosa
70   versicolor  versicolor
108   virginica   virginica
137   virginica   virginica
46       setosa      setosa
37       setosa      setosa
82   versicolor  versicolor
120   virginica   virginica
63   versicolor  versicolor
119   virginica  versicolor
129   virginica   virginica
138   virginica  versicolor
97   versicolor  versicolor
80   versicolor  versicolor
101   virginica   virginica
140   virginica   virginica
126   virginica   virginica
79   versicolor  versicolor
22       setosa      setosa
139   virginica   virginica
74   versicolor  versicolor
45       setosa      setosa
36       setosa      setosa
5        setosa      setosa
17       setosa      setosa
102   virginica   virginica
124   virginica   virginica
76   versicolor  versicolor
132   virginica   virginica
116   virginica   virginica
95   versicolor  versicolor

In [46]:
dataex[dataex.true != dataex.pred]

true        pred
106   virginica  versicolor
77   versicolor   virginica
119   virginica  versicolor
138   virginica  versicolor

In [42]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [49]:
print(confusion_matrix(y_test, pred))

[[12  0  0]
 [ 0 15  1]
 [ 0  3 14]]


In [52]:
dataex.pred.value_counts()

versicolor    18
virginica     15
setosa        12
Name: pred, dtype: int64

In [64]:
print(accuracy_score(y_test, pred))

0.9111111111111111


In [53]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.83      0.94      0.88        16
   virginica       0.93      0.82      0.87        17

    accuracy                           0.91        45
   macro avg       0.92      0.92      0.92        45
weighted avg       0.92      0.91      0.91        45



In [54]:
modello=LogisticRegression()

In [57]:
modello.fit(X_train,y_train)

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [58]:
pred_lo=modello.predict(X_test)

In [59]:
pred_lo

array(['virginica', 'versicolor', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'virginica', 'virginica', 'setosa', 'setosa',
       'versicolor', 'virginica', 'versicolor', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor',
       'setosa', 'setosa', 'setosa', 'setosa', 'virginica', 'virginica',
       'versicolor', 'virginica', 'virginica', 'versicolor'], dtype=object)

In [60]:
print(confusion_matrix(y_test, pred_lo))

[[12  0  0]
 [ 0 14  2]
 [ 0  2 15]]


In [61]:
print(classification_report(y_test, pred_lo))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.88      0.88      0.88        16
   virginica       0.88      0.88      0.88        17

    accuracy                           0.91        45
   macro avg       0.92      0.92      0.92        45
weighted avg       0.91      0.91      0.91        45



In [63]:
print(accuracy_score(y_test, pred_lo))

0.9111111111111111
