In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [26]:
data = pd.read_csv('https://github.com/prasertcbs/basic-dataset/raw/master/ISLR/Auto.csv',na_values='?')

In [27]:
data.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0       130.0    3504          12.0    70   
1  15.0          8         350.0       165.0    3693          11.5    70   
2  18.0          8         318.0       150.0    3436          11.0    70   
3  16.0          8         304.0       150.0    3433          12.0    70   
4  17.0          8         302.0       140.0    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [28]:
min(data['mpg'])

9.0

In [29]:
max(data['mpg'])

46.6

In [30]:
data.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  397.000000  397.000000    397.000000  392.000000   397.000000   
mean    23.515869    5.458438    193.532746  104.469388  2970.261965   
std      7.825804    1.701577    104.379583   38.491160   847.904119   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.000000   75.000000  2223.000000   
50%     23.000000    4.000000    146.000000   93.500000  2800.000000   
75%     29.000000    8.000000    262.000000  126.000000  3609.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration        year      origin  
count    397.000000  397.000000  397.000000  
mean      15.555668   75.994962    1.574307  
std        2.749995    3.690005    0.802549  
min        8.000000   70.000000    1.000000  
25%       13.800000   73.000000    1.000000  
50%       15.500000   76.000000    1.000000  
75%       17.100000   79.000000    2.000000  
max       24.800000   82.000000    3.000000

In [31]:
data.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      5
weight          0
acceleration    0
year            0
origin          0
name            0
dtype: int64

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           397 non-null    float64
 1   cylinders     397 non-null    int64  
 2   displacement  397 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        397 non-null    int64  
 5   acceleration  397 non-null    float64
 6   year          397 non-null    int64  
 7   origin        397 non-null    int64  
 8   name          397 non-null    object 
dtypes: float64(4), int64(4), object(1)
memory usage: 28.0+ KB


In [33]:
data.dropna(inplace=True)

In [34]:
sns.pairplot(data[['mpg','horsepower','weight']])

In [35]:
data[['mpg', 'horsepower', 'weight']].corr()

mpg  horsepower    weight
mpg         1.000000   -0.778427 -0.832244
horsepower -0.778427    1.000000  0.864538
weight     -0.832244    0.864538  1.000000

In [36]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [37]:
X = data[['horsepower','weight']]
y = data['mpg']

In [38]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [39]:
X_train

horsepower  weight
335        88.0    2500
396        82.0    2720
393        52.0    2130
29         88.0    2130
275       125.0    3140
..          ...     ...
205        75.0    2155
257        90.0    3210
73        130.0    4098
237        63.0    2051
38        165.0    4209

[274 rows x 2 columns]

In [40]:
lm = LinearRegression()
lm

LinearRegression()

In [41]:
lm.fit(X_train,y_train)

LinearRegression()

In [42]:
lm.score(X_train,y_train)

0.6932437089290189

In [43]:
lm.score(X_test,y_test)

0.7292547386704166

In [44]:
lm.coef_

array([-0.04898144, -0.00553451])

In [45]:
poly = PolynomialFeatures(degree=2, include_bias=True)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

pm = LinearRegression()
pm.fit(X_train_poly, y_train)

LinearRegression()

In [48]:
poly.get_feature_names()

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['1', 'x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']

In [46]:
X_train_poly

array([[1.0000000e+00, 8.8000000e+01, 2.5000000e+03, 7.7440000e+03,
        2.2000000e+05, 6.2500000e+06],
       [1.0000000e+00, 8.2000000e+01, 2.7200000e+03, 6.7240000e+03,
        2.2304000e+05, 7.3984000e+06],
       [1.0000000e+00, 5.2000000e+01, 2.1300000e+03, 2.7040000e+03,
        1.1076000e+05, 4.5369000e+06],
       ...,
       [1.0000000e+00, 1.3000000e+02, 4.0980000e+03, 1.6900000e+04,
        5.3274000e+05, 1.6793604e+07],
       [1.0000000e+00, 6.3000000e+01, 2.0510000e+03, 3.9690000e+03,
        1.2921300e+05, 4.2066010e+06],
       [1.0000000e+00, 1.6500000e+02, 4.2090000e+03, 2.7225000e+04,
        6.9448500e+05, 1.7715681e+07]])

In [47]:
X_train

horsepower  weight
335        88.0    2500
396        82.0    2720
393        52.0    2130
29         88.0    2130
275       125.0    3140
..          ...     ...
205        75.0    2155
257        90.0    3210
73        130.0    4098
237        63.0    2051
38        165.0    4209

[274 rows x 2 columns]

In [49]:
pm.coef_

array([ 0.00000000e+00, -2.71309036e-01, -8.77290010e-03,  2.15169279e-04,
        4.22566829e-05, -3.58954387e-08])

In [50]:
pm.score(X_train_poly, y_train)

0.7344640327916464

In [51]:
pm.score(X_test_poly, y_test)

0.773456757844117

In [55]:
X_test[:3]

horsepower  weight
82         97.0    2506
167        75.0    2171
356        75.0    2350

In [54]:
X_test_poly[:3]

array([[1.000000e+00, 9.700000e+01, 2.506000e+03, 9.409000e+03,
        2.430820e+05, 6.280036e+06],
       [1.000000e+00, 7.500000e+01, 2.171000e+03, 5.625000e+03,
        1.628250e+05, 4.713241e+06],
       [1.000000e+00, 7.500000e+01, 2.350000e+03, 5.625000e+03,
        1.762500e+05, 5.522500e+06]])

In [56]:
lm.predict(X_test[:3])

array([26.20179173, 29.13344391, 28.14276685])

In [57]:
pm.predict(X_test_poly[:3])

array([24.76871606, 29.52708203, 28.49498017])

In [58]:
y_test

82     23.0
167    29.0
356    32.4
120    19.0
384    38.0
       ... 
60     20.0
12     15.0
305    28.4
165    20.0
92     13.0
Name: mpg, Length: 118, dtype: float64

In [59]:
pm.predict(poly.fit_transform([[97, 2506]]))

array([24.76871606])